Connect form to firebase
codetapacademy/betonme.uk pull request #19
Opened 2021-07-13 20:05 UTC by biggicode

2021-07-19 17:59 UTC, MariaTeo approved these changes

2021-07-19 20:12 UTC, marianzburlea requested changes
small updates :)
please clean up the code

2021-07-19 20:12 UTC, marianzburlea commented on src/component/auction-page/auction-page.component.jsx
> +  const location = useLocation();
you are no longer using location

2021-07-19 20:12 UTC, marianzburlea commented on src/component/auction-page/auction-page.component.jsx
> +  const { title, StartingPrice } = location.state;
`title` and `StartingPrice` are not used in this file

2021-07-19 20:12 UTC, marianzburlea commented on src/component/auction-page/auction-page.component.jsx
> +  console.log(auction);
remove console.log

2021-07-19 20:12 UTC, marianzburlea commented on src/component/auctions/auctions.component.jsx
> +        })}
you can have implicit return

2021-07-21 09:57 UTC, marianzburlea requested changes
further cleaning of the code is required

2021-07-21 09:57 UTC, marianzburlea commented on src/component/action-card/action-card.component.jsx
> +export const ActionCard = ({id}) => {
please use the formatter, `CTRL + SHIFT + F`, it's not that difficult.
also make a note somewhere so I don't have to remind you so many times.

2021-07-21 09:57 UTC, marianzburlea commented on src/component/action-card/action-card.component.jsx
> +        {/* <ACS.ProductName>{title}</ACS.ProductName> */}
remove comments

2021-07-21 09:57 UTC, marianzburlea commented on src/component/action-card/action-card.component.jsx
> +            {/* <ACS.PriceValue>$ {startingPrice}</ACS.PriceValue> */}
remove comments

2021-07-21 09:57 UTC, marianzburlea commented on src/component/sell/sell.component.jsx
> +    resetForm({ values: ''})
why do you pass an object with a key *values* and an empty string as value?

2021-07-21 09:57 UTC, marianzburlea commented on src/component/sell/sell.form.js
> +export const initialValues = {title: '', images: '', description: '', startingPrice: '', currency: '', city: '', email: '', phone: ''}
use the formatter again.

2021-07-26 09:35 UTC, marianzburlea requested changes

2021-07-26 09:35 UTC, marianzburlea commented on src/component/auction-card/auction-card.component.jsx
> +  const [CardData, setCardData] = useState({});
`CardData` => `cardData`

2021-07-26 09:35 UTC, marianzburlea commented on src/component/auctions/auctions.component.jsx
> +    });
unsubscribe from the stream as well.

2021-07-26 09:35 UTC, marianzburlea commented on src/component/home/home.component.jsx
> +    });
unsubscribe in useEffect

2021-07-26 09:35 UTC, marianzburlea commented on src/component/home/home.component.jsx
> +      <div
why css in js when you use styled-components?

2021-07-26 10:03 UTC, tandaraelena commented on src/component/auction-card/auction-card.component.jsx
> +import Image from "../../asset/images/bicycle.jpg";
Image => image

2021-07-26 10:03 UTC, tandaraelena commented on src/component/sell/sell.component.jsx
> +        enebleReinitialize
Maybe a typo for 'enableReinitialize' ?

2021-07-26 11:30 UTC, QuintyHH commented on src/component/app/app.component.jsx
> +export { App };
Any reason we are exporting like this?
If you want a named export, just use the keyword 'export' when declaring the App component (line 18).
If you want a default export, use 'export default App' here.

Your current implementation exports a new Object that has App as property. No reason to declare this new Object.

2021-07-26 11:34 UTC, QuintyHH commented on src/component/auction-page/auction-page.component.jsx
>          {!isLoggedIn && <S.LogInButton>Log In</S.LogInButton>}
No need to check isLoggedIn twice, you can replace this with 
{ isLoggedIn $$ (
  <>
        <S.RegisterButton>Register </S.RegisterButton>
        <S.LogInButton>Log In</S.LogInButton>
  </>)}

2021-07-26 11:35 UTC, QuintyHH commented on src/component/auctions/auctions.component.jsx
> +  console.log(auctionsList);
Hello, console :D

2021-07-26 11:36 UTC, QuintyHH commented on src/component/home/home.component.jsx
> +    console.log(value);
Hello, console :D

2021-07-26 11:37 UTC, QuintyHH commented on src/component/home/home.component.jsx
> +        anaaremere: Math.random() - 0.5 > 0,
Let's leave poor Ana and her apples and lets change this to something that makes a bit more sense in this context :D

2021-07-26 11:37 UTC, QuintyHH commented on src/component/home/home.component.jsx
> +    console.log(e, Object.keys(e));
Hello, console :D

2021-07-26 11:39 UTC, QuintyHH commented on src/component/home/home.component.jsx
> +          {isLoggedIn && (
No need to check isLoggedIn twice, we can use a ternary here. 
{!isLoggedIn 
? <HOS.PosterButton onClick={logheazaMa}>Register</HOS.PosterButton> 
: <HOS.PosterButton onClick={scoateMa}>LogOUT</HOS.PosterButton>}
}

2021-07-26 11:43 UTC, QuintyHH commented on src/component/sell/sell.component.jsx
>                  </div>
What's the point of this wrapper div?

2021-07-26 11:43 UTC, QuintyHH commented on src/component/sell/sell.component.jsx
>                    <S.StyledLabel>Starting Price</S.StyledLabel>
You're only returning one component, no need for the Fragments

2021-07-26 11:44 UTC, QuintyHH commented on src/component/sell/sell.component.jsx
>                    <S.StyledLabel>Your city</S.StyledLabel>
No need for the wrapper div

2021-07-26 11:45 UTC, QuintyHH commented on src/component/sign-in/sign-in.component.jsx
> +      console.log(uid, displayName, photoURL, email);
Hello, console :D

2021-07-26 11:46 UTC, QuintyHH commented on src/component/sign-in/sign-in.component.jsx
> +      console.log(error, "Ceva nu merge");
To increase visibility in dev tools, you can actually use console.error

2021-07-26 11:47 UTC, QuintyHH commented on src/component/sign-in/sign-in.component.jsx
> +  };
const closePopUp => userData && closeSignIn() 

Looks cleaner

2021-07-26 11:48 UTC, QuintyHH commented on src/component/sign-in/sign-in.component.jsx
> +      console.log(result);
Hello, console! :D

2021-07-26 11:49 UTC, QuintyHH commented on src/component/sign-in/sign-in.style.js
>    border: none;
Why set border radius of 6px, if you are setting the border to none?

2021-07-28 19:40 UTC, marianzburlea approved these changes

2021-07-28 20:13 UTC, tandaraelena approved these changes

2021-08-03 12:21 UTC, merged